version: '3.7'

networks:
    pentesting:
        driver: bridge

volumes: 
    webgoat:
    dbwap:
    bwapp:
    wpress:

services:

    wodpress:
        container_name: vulwps
        image: l505/vulnerablewordpress
        restart: on-failure
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8086:80
            - 3306:3306
        volumes: 
            - wpress:/var/www/
        networks: 
            - pentesting

    ninjaweb:
    
        container_name: ninjaweb
        image: opendns/security-ninjas
        restart: on-failure
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8899:80
        networks: 
            - pentesting

    webgoat:

        container_name: webgoat
        image: webgoat/webgoat-8.0
        restart: on-failure
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8080:8080
        volumes: 
            - webgoat:/var/www/
        networks: 
            - pentesting
    
    dvwap:

        container_name: dvwap
        image: vulnerables/web-dvwa
        restart: on-failure
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8081:80
        volumes: 
            - dbwap:/var/www/
        networks: 
            - pentesting
    
    bwapp:

        container_name: bwapp
        image: feltsecure/owasp-bwapp
        restart: on-failure
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8082:80
        volumes: 
            - bwapp:/var/www/
        networks: 
            - pentesting
    
    shop:

        container_name: juiceshop
        image: bkimminich/juice-shop
        restart: on-failure
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8083:3000
        networks: 
            - pentesting
            
    bricks:
        container_name: bricks
        image: citizenstig/owaspbricks
        restart: on-failure 
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8084:80
        networks: 
            - pentesting
    
    owasp:
        container_name: owasp17
        image: bltsec/mutillidae-docker
        restart: on-failure
        mem_limit: 200m
        cpus: 0.5
        ports: 
            - 8088:80
            - 443:443
        networks: 
            - pentesting