version: '3.7'



networks:
  default:
    external: true
    name: pentesting

services:

    cadvisor:
        image: google/cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - 8085:8080
        restart: always
        mem_limit: 200m
        cpus: 0.5
        networks: 
            - pentesting